# Variables needed for this script are stored on Travis Settings
#  - For all environments:
#    - AWS_DEFAULT_REGION
#  - For dev environment:
#    - AWS_ACCOUNT_USER_ID_DEV
#    - AWS_ACCOUNT_SECRET_DEV
#    - AWS_PROFILE_DEV
#  - For Demo environment:
#   - AWS_ACCOUNT_USER_ID_DEMO
#   - AWS_ACCOUNT_SECRET_DEMO
#   - AWS_PROFILE_DEMO
# - For Prod environment:
#   - AWS_ACCOUNT_USER_ID_PROD
#   - AWS_ACCOUNT_SECRET_PROD
#   - AWS_PROFILE_PROD

language: go

go:
 - 1.12.x

before_install:
 - curl -sf https://up.apex.sh/install | sudo sh
 - pip install --user awscli
 - export PATH=$PATH:$HOME/.local/bin

services:
 - docker

install:
 - go get -t ./...
 - sudo apt-get install jq -y

after_success:
 - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
 - go test -v ./...

deploy:
 # dev
 - provider: script
   script: aws configure set profile.$AWS_PROFILE_DEV.aws_access_key_id $AWS_ACCOUNT_USER_ID_DEV && aws configure set profile.$AWS_PROFILE_DEV.aws_secret_access_key $AWS_ACCOUNT_SECRET_DEV && aws configure set profile.$AWS_PROFILE_DEV.region $AWS_DEFAULT_REGION && aws configure --profile $AWS_PROFILE_DEV list && TRAVIS_AWS_PROFILE=$AWS_PROFILE_DEV make dev
   edge: true
   on:
     branch: master
 # demo
 - provider: script
   script: aws configure set profile.$AWS_PROFILE_DEMO.aws_access_key_id $AWS_ACCOUNT_USER_ID_DEMO && aws configure set profile.$AWS_PROFILE_DEMO.aws_secret_access_key $AWS_ACCOUNT_SECRET_DEMO && aws configure set profile.$AWS_PROFILE_DEMO.region $AWS_DEFAULT_REGION && aws configure --profile $AWS_PROFILE_DEMO list && TRAVIS_AWS_PROFILE=$AWS_PROFILE_DEMO make demo
   edge: true
   on:
     branch: master
     tags: true
 # prod
 - provider: script
   script: aws configure set profile.$AWS_PROFILE_PROD aws_access_key_id $AWS_ACCOUNT_USER_ID_PROD && aws configure set profile.$AWS_PROFILE_PROD.aws_secret_access_key $AWS_ACCOUNT_SECRET_PROD && aws configure set profile.$AWS_PROFILE_PROD.region $AWS_DEFAULT_REGION && aws configure --profile $AWS_PROFILE_PROD list && TRAVIS_AWS_PROFILE=$AWS_PROFILE_PROD make prod
   edge: true
   on:
     branch: master
     tags: true

env:
 - GO112MODULE=on